### ISSUE TITLE
generating report for pSINSCID_UK01 was not successful

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/geneTherapyPatientReportMaker#2]
Generating report from the following sets
   sampleName     GTSP       patient    celltype timepoint
1  GTSP0436-1 GTSP0436 pSINSCID_UK01        PBMC        m6
2  GTSP0436-2 GTSP0436 pSINSCID_UK01        PBMC        m6
3  GTSP0436-3 GTSP0436 pSINSCID_UK01        PBMC        m6
4  GTSP0436-4 GTSP0436 pSINSCID_UK01        PBMC        m6
5  GTSP0437-1 GTSP0437 pSINSCID_UK01 Neutrophils        m6
6  GTSP0437-2 GTSP0437 pSINSCID_UK01 Neutrophils        m6
7  GTSP0437-3 GTSP0437 pSINSCID_UK01 Neutrophils        m6
8  GTSP0437-4 GTSP0437 pSINSCID_UK01 Neutrophils        m6
9  GTSP0438-1 GTSP0438 pSINSCID_UK01      Tcells        m6
10 GTSP0438-2 GTSP0438 pSINSCID_UK01      Tcells        m6
11 GTSP0438-3 GTSP0438 pSINSCID_UK01      Tcells        m6
12 GTSP0438-4 GTSP0438 pSINSCID_UK01      Tcells        m6
13 GTSP0440-1 GTSP0440 pSINSCID_UK01     NKcells        m6
14 GTSP0440-2 GTSP0440 pSINSCID_UK01     NKcells        m6
15 GTSP0440-3 GTSP0440 pSINSCID_UK01     NKcells        m6
16 GTSP0440-4 GTSP0440 pSINSCID_UK01     NKcells        m6
17 GTSP0441-1 GTSP0441 pSINSCID_UK01   Monocytes        m6
18 GTSP0441-2 GTSP0441 pSINSCID_UK01   Monocytes        m6
19 GTSP0441-3 GTSP0441 pSINSCID_UK01   Monocytes        m6
20 GTSP0441-4 GTSP0441 pSINSCID_UK01   Monocytes        m6
Error in rep(1:length(tframe.list), sapply(tframe.list, nrow)) :
  invalid 'times' argument
Calls: lapply ... lapply -> FUN -> getEstimatedAbundance -> estAbund -> factor
Execution halted

**Comment by anatolydryga** [comment]
is it standard factor vs character problem?

**Comment by yhwu** [comment]
Good guess, I will check tomorrow.

**Comment by yhwu** [comment]
It turns out to be NULL objects again. Reason was that some replicates didn't have any sites. Easy to fix.
