### ISSUE TITLE
master had error, counts no error

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/geneTherapyPatientReportMaker#34]
please generate all reports before merge

p03712-08.log:Execution halted
p04409-18.log:Execution halted
p04409-26.log:Execution halted
p959-101.log:Execution halted
pFR03.log:Execution halted
pSINSCID_UK01.log:Execution halted
pWAS00002.log:Execution halted

**Comment by anatolydryga** [comment]
@yhwu 

did intSiteRetriever from db_schema was used?

e.g.  devtools::install_github('BushmanLab/intSiteRetriever', ref='db_schema')

**Comment by yhwu** [comment]
master, from microb237 database, Chris?
error message:

67 GTSP0805-3 GTSP0805   pFR03          Tcells       m36
68 GTSP0805-4 GTSP0805   pFR03          Tcells       m36
Fetching unique sites and estimating abundance
Clustering by minimum overlap.
     - Adding clustered value frequencies.
Adding clustered data back to psl.rd.
Picking best scoring hit to represent a cluster.
Cleaning up!
Error in `[[<-`(`*tmp*`, name, value = c(1, 2, 1, 2, 3, 5, 2, 2, 2, 2,  : 
  2873 elements in value to replace 2872 elements
Calls: lapply ... getEstimatedAbundance -> $<- -> $<- -> [[<- -> [[<-
Execution halted

**Comment by anatolydryga** [comment]
seems to be fixed by @cnobles?
